# Neural Network Assignment 
### Comprison With 5 Classification Models 

By Sumanth Sripada

In [4]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

In [5]:
pip install tensorflow

In [6]:
import tensorflow as tf

In [9]:
#Machine Learning Models
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

In [15]:
data = pd.read_csv('C:/Users/saisu/OneDrive/Desktop/SML_Section7/SML_Section7/data/bankruptcy_prediction/data.csv')

In [16]:
data.head()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          
2          1                                           0.426071          
3          1                                           0.399844          
4          1                                           0.465022          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   
2                                 0.499019   
3                                 0.451265   
4                                 0.538432   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    
2                                           0.472295    
3                                           0.457733    
4                                           0.522298    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   
2                 0.601450                      0.601364   
3                 0.583541                      0.583541   
4                 0.598783                      0.598783   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   
2                0.998857                    0.796403   
3                0.998700                    0.796967   
4                0.998973                    0.797366   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   
2                      0.808388                                      0.302035   
3                      0.808966                                      0.303350   
4                      0.809304                                      0.303475   

   ...   Net Income to Total Assets   Total assets to GNP price  \
0  ...                     0.716845                    0.009219   
1  ...                     0.795297                    0.008323   
2  ...                     0.774670                    0.040003   
3  ...                     0.739555                    0.003252   
4  ...                     0.795016                    0.003878   

    No-credit Interval   Gross Profit to Sales  \
0             0.622879                0.601453   
1             0.623652                0.610237   
2             0.623841                0.601449   
3             0.622929                0.583538   
4             0.623521                0.598782   

    Net Income to Stockholder's Equity   Liability to Equity  \
0                             0.827890              0.290202   
1                             0.839969              0.283846   
2                             0.836774              0.290189   
3                             0.834697              0.281721   
4                             0.839973              0.278514   

    Degree of Financial Leverage (DFL)  \
0                             0.026601   
1                             0.264577   
2                             0.026555   
3                             0.026697   
4                             0.024752   

    Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
0                                           0.564050                   1   
1                                           0.570175                   1   
2                                           0.563706                   1   
3                                           0.564663                   1   
4                        

In [17]:
data.isna().sum()

Bankrupt?                                                   0
 ROA(C) before interest and depreciation before interest    0
 ROA(A) before interest and % after tax                     0
 ROA(B) before interest and depreciation after tax          0
 Operating Gross Margin                                     0
                                                           ..
 Liability to Equity                                        0
 Degree of Financial Leverage (DFL)                         0
 Interest Coverage Ratio (Interest expense to EBIT)         0
 Net Income Flag                                            0
 Equity to Liability                                        0
Length: 96, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = data.loc[:, data.columns != 'Bankrupt?']
y = data['Bankrupt?']

In [21]:
#Split data into train-test(20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [25]:
X_train.shape ,X_test.shape

((5455, 95), (1364, 95))

In [24]:
y_train.shape

(5455,)

NN Model with 1 hidden layer of 30 neurons , activation function - sigmoid

In [26]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(30, input_dim=95, activation='sigmoid'),
  tf.keras.layers.Dense(10)                                       
])

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                2880      
                                                                 
 dense_1 (Dense)             (None, 10)                310       
                                                                 
Total params: 3,190
Trainable params: 3,190
Non-trainable params: 0
_________________________________________________________________


In [28]:
#predictions
predictions = model(np.array(X_train[:1]))
predictions

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ 0.44325733, -0.27435243,  0.71660435,  1.17753   , -0.22243267,
        -1.5920134 , -0.3397721 , -0.53975785, -0.6380731 ,  1.1833768 ]],
      dtype=float32)>

In [29]:
# Return prediction as a vector of probability
tf.nn.softmax(predictions).numpy()

array([[0.1136708 , 0.05546193, 0.14940393, 0.23688607, 0.05841757,
        0.01485054, 0.05194976, 0.04253348, 0.03855077, 0.23827514]],
      dtype=float32)

In [30]:
# Loss Function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.1744485

In [31]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [32]:
# Train the model
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
171/171 [==============================] - 0s 628us/step - loss: 0.7357 - accuracy: 0.8643
Epoch 2/5
171/171 [==============================] - 0s 622us/step - loss: 0.2244 - accuracy: 0.9677
Epoch 3/5
171/171 [==============================] - 0s 716us/step - loss: 0.1842 - accuracy: 0.9677
Epoch 4/5
171/171 [==============================] - 0s 698us/step - loss: 0.1707 - accuracy: 0.9677
Epoch 5/5
171/171 [==============================] - 0s 622us/step - loss: 0.1640 - accuracy: 0.9677


In [33]:
# Model Evaluation Train
model.evaluate(X_train,  y_train, verbose=2)

171/171 - 0s - loss: 0.1612 - accuracy: 0.9677 - 167ms/epoch - 977us/step


[0.1611965149641037, 0.967736005783081]

In [34]:
# Model Evalution Test
model.evaluate(X_test,  y_test, verbose=2)

43/43 - 0s - loss: 0.1561 - accuracy: 0.9677 - 31ms/epoch - 718us/step


[0.15612338483333588, 0.9677419066429138]

In [35]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [36]:
#predictions
y_test_pred = probability_model(np.array(X_test))
y_test_pred = y_test_pred.numpy()
y_test_pred[:5]

array([[9.51155961e-01, 4.14252318e-02, 2.66122399e-03, 9.47188353e-04,
        8.56169267e-04, 1.26398474e-04, 1.30099314e-03, 5.59236505e-04,
        2.55558261e-04, 7.12124398e-04],
       [9.61066544e-01, 3.36946398e-02, 1.83814648e-03, 7.49143073e-04,
        4.39799594e-04, 1.04369254e-04, 1.16147567e-03, 6.75463525e-04,
        1.08559660e-04, 1.61812670e-04],
       [9.75487590e-01, 2.07755398e-02, 4.35003487e-04, 8.12849263e-04,
        7.59864401e-04, 1.18058757e-04, 3.99009587e-04, 5.05289936e-04,
        1.67698861e-04, 5.39069704e-04],
       [9.51376259e-01, 4.00217101e-02, 6.34657685e-04, 2.64013093e-03,
        1.09329249e-03, 3.05972819e-04, 8.28536286e-04, 4.38723277e-04,
        5.58947970e-04, 2.10184883e-03],
       [9.74538505e-01, 2.31162123e-02, 7.87877187e-04, 2.40059817e-04,
        1.86721969e-04, 5.34380997e-05, 4.05539293e-04, 1.41289522e-04,
        1.05296989e-04, 4.24990605e-04]], dtype=float32)

### Q3: Build a deep NN model with multiple hidden layers (of your choice) and sigmoid activation function.

In [38]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(100, input_dim=95, activation='sigmoid'), 
  tf.keras.layers.Dense(50, activation='sigmoid'),
  tf.keras.layers.Dense(20, activation='sigmoid'),
  tf.keras.layers.Dense(10)                                       
])

In [40]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 100)               9600      
                                                                 
 dense_7 (Dense)             (None, 50)                5050      
                                                                 
 dense_8 (Dense)             (None, 20)                1020      
                                                                 
 dense_9 (Dense)             (None, 10)                210       
                                                                 
Total params: 15,880
Trainable params: 15,880
Non-trainable params: 0
_________________________________________________________________


In [41]:
#predictions
predictions = model(np.array(X_train))
predictions

<tf.Tensor: shape=(5455, 10), dtype=float32, numpy=
array([[ 0.3161849 ,  0.7032774 ,  0.05213815, ...,  0.57483745,
        -0.26901418,  0.5004026 ],
       [ 0.29375604,  0.6459809 ,  0.07167967, ...,  0.5941301 ,
        -0.29430604,  0.4856464 ],
       [ 0.308604  ,  0.6798595 ,  0.07861611, ...,  0.5818597 ,
        -0.31928998,  0.51432925],
       ...,
       [ 0.25700617,  0.67742115,  0.10500608, ...,  0.5724947 ,
        -0.3052978 ,  0.46225291],
       [ 0.27269217,  0.6378217 ,  0.10231256, ...,  0.59221333,
        -0.29033476,  0.5234034 ],
       [ 0.2822383 ,  0.69002855,  0.07268924, ...,  0.57884705,
        -0.2809038 ,  0.45101726]], dtype=float32)>

In [43]:
#loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train, predictions).numpy()

2.348396

In [45]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [47]:
# Train the model
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
171/171 [==============================] - 0s 739us/step - loss: 0.1248 - accuracy: 0.9676
Epoch 2/100
171/171 [==============================] - 0s 727us/step - loss: 0.1240 - accuracy: 0.9679
Epoch 3/100
171/171 [==============================] - 0s 862us/step - loss: 0.1232 - accuracy: 0.9683
Epoch 4/100
171/171 [==============================] - 0s 968us/step - loss: 0.1225 - accuracy: 0.9685
Epoch 5/100
171/171 [==============================] - 0s 1ms/step - loss: 0.1224 - accuracy: 0.9676
Epoch 6/100
171/171 [==============================] - 0s 1ms/step - loss: 0.1214 - accuracy: 0.9687
Epoch 7/100
171/171 [==============================] - 0s 943us/step - loss: 0.1208 - accuracy: 0.9692
Epoch 8/100
171/171 [==============================] - 0s 945us/step - loss: 0.1207 - accuracy: 0.9683
Epoch 9/100
171/171 [==============================] - 0s 880us/step - loss: 0.1210 - accuracy: 0.9698
Epoch 10/100
171/171 [==============================] - 0s 1ms/step - loss: 0

171/171 [==============================] - 0s 739us/step - loss: 0.0823 - accuracy: 0.9760
Epoch 80/100
171/171 [==============================] - 0s 733us/step - loss: 0.0808 - accuracy: 0.9765
Epoch 81/100
171/171 [==============================] - 0s 727us/step - loss: 0.0824 - accuracy: 0.9760
Epoch 82/100
171/171 [==============================] - 0s 833us/step - loss: 0.0813 - accuracy: 0.9751
Epoch 83/100
171/171 [==============================] - 0s 926us/step - loss: 0.0805 - accuracy: 0.9771
Epoch 84/100
171/171 [==============================] - 0s 945us/step - loss: 0.0812 - accuracy: 0.9765
Epoch 85/100
171/171 [==============================] - 0s 932us/step - loss: 0.0804 - accuracy: 0.9751
Epoch 86/100
171/171 [==============================] - 0s 704us/step - loss: 0.0792 - accuracy: 0.9767
Epoch 87/100
171/171 [==============================] - 0s 710us/step - loss: 0.0800 - accuracy: 0.9756
Epoch 88/100
171/171 [==============================] - 0s 716us/step - loss:

In [58]:
# Model Evaluation Train
train_result = model.evaluate(X_train,  y_train, verbose=2)

train_eval = pd.DataFrame({"Train_Accuracy":train_result[1]}, index = ['Neural Network'])
train_eval

171/171 - 0s - loss: 0.0694 - accuracy: 0.9762 - 87ms/epoch - 507us/step


Train_Accuracy
Neural Network        0.976169

In [59]:
# Model Evaluation Test
test_result = model.evaluate(X_test,  y_test, verbose=2)

#set into df
test_eval = pd.DataFrame({"Test_Accuracy":test_result[1]}, index = ['Neural Network'])
test_eval

43/43 - 0s - loss: 0.2164 - accuracy: 0.9619 - 33ms/epoch - 758us/step


Test_Accuracy
Neural Network       0.961877

### Q4: Build Other 5 Classification models and compare

In [69]:
#Models

logistic      = LogisticRegression()
decision_tree = DecisionTreeClassifier()
neural_net    = MLPClassifier()
random_forest = RandomForestClassifier(n_estimators =500)
KNN           = KNeighborsClassifier()

models = {
          "logistic"      : logistic,
          "decision_tree" : decision_tree,
          "random_forest" : random_forest,
          "neural_net"    : neural_net,
          "KNN"           : KNN
         }

In [70]:
for model in models:
    random.seed=1
    models[model].fit(X_train, y_train.values.ravel())
    print(f"{model}     has been trained successfully")

c:\users\saisu\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


logistic     has been trained successfully
decision_tree     has been trained successfully
random_forest     has been trained successfully
neural_net     has been trained successfully
KNN     has been trained successfully


## TRAIN EVALUATION

In [74]:
#Test Evaluation
performances = {}

for model in models:
    predictions   = models[model].predict(X_train)
    accuracy      = accuracy_score(y_train, predictions)
    performances[model] = {"Train_Accuracy":accuracy}

train_eval_models = pd.DataFrame(performances).transpose()

## TEST EVALUATION

In [73]:
# Test Evaluation
performances = {}

for model in models:
    random.seed=1
    predictions   = models[model].predict(X_test)
    accuracy      = accuracy_score(y_test, predictions)
    performances[model] = {"Test_Accuracy":accuracy}

test_eval_models = pd.DataFrame(performances).transpose()

In [76]:
#Compare Train and Test
eval_merged = train_eval_models.merge(test_eval_models, left_index=True, right_index=True)

## COMPARING ALL THE MODELS PERFORMANCE

In [77]:
eval_merged.append(train_eval).sort_values(by="Test_Accuracy", ascending=False)

Train_Accuracy  Test_Accuracy
KNN                   0.969386       0.968475
random_forest         1.000000       0.965543
logistic              0.962603       0.963343
decision_tree         1.000000       0.950147
neural_net            0.964436       0.948680
Neural Network        0.976169            NaN